name: Dry run on kind

on:
  push:
  pull_request:
    branches: [ main ]
env:
  K8S_VERSION: "1.33.0"
jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install kind
        run: |
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
          chmod +x ./kind
          ./kind version
      - name: install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v${K8S_VERSION}/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          ./kubectl version --client
      - name: create kind cluster
        run: kind create cluster --config=./ci/kind-config.yaml
