name: Dry run on kind

on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello
        run: |
          docker run -it hello-world
