name: Validate manifest

on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  dry-run-on-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install kind
        run: |
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
          chmod +x ./kind
          ./kind version
      - name: install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          ./kubectl version --client
      - name: create kind cluster
        run: |
          ./kind create cluster --config=./ci/kind-config.yaml
          kubectl version
      - name: dry run
        run: |
          kubectl apply -f ./manifest/pod.yaml --dry-run=server
